services:
  init-db:
    image: "postgres:10.5-alpine"
    env_file:
      - ./variables.env
    volumes:
      - ./leilao-api/src/main/resources/sql:/app/data
    command:
      - "sh"
      - "-c"
      - |
        psql -h postgresql -w -d az -v ON_ERROR_STOP=1 -f /app/data/001_create_db_tables.sql
        psql -h postgresql -w -d az -v ON_ERROR_STOP=1 -f /app/data/002_initial_data_insert.sql
    depends_on:
      postgresql:
        condition: service_healthy
    networks:
      - app-network
  postgresql:
    image: "postgres:10.5-alpine"
    ports:
      - "5432:5432"
    volumes:
      - "postgresqldata:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    env_file:
      - ./variables.env
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=az
    networks:
      - app-network
  leilao-api:
    build:
      context: ./leilao-api
      dockerfile: Dockerfile
    container_name: leilao-api
    ports:
      - "8080:8080"
    env_file:
      - ./variables.env
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/az
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
    depends_on:
      postgresql:
        condition: service_healthy
      init-db:
        condition: service_completed_successfully
    networks:
      - app-network
  leilao-app:
    build:
      context: ./leilao-app
      dockerfile: Dockerfile
    container_name: leilao-app
    ports:
      - "3000:80"
    depends_on:
      - leilao-api
    networks:
      - app-network
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8888:8080"
    networks:
      - app-network
volumes:
  postgresqldata: null
networks:
  app-network:
    driver: bridge
