CREATE TABLE empresa (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    razaoSocial VARCHAR(64) NOT NULL,
    cnpj VARCHAR(32) UNIQUE NOT NULL,
    logradouro VARCHAR(64),
    municipio VARCHAR(64),
    numero VARCHAR(10),
    complemento VARCHAR(64),
    bairro VARCHAR(64),
    telefone VARCHAR(32),
    email VARCHAR(254) NOT NULL,
    site VARCHAR(254),
    usuario VARCHAR(20) UNIQUE NOT NULL,
    senha VARCHAR(128),
    createdAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE TABLE leilao (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    codigo INTEGER,
    descricao VARCHAR(60) NOT NULL,
    vendedor INTEGER NOT NULL,
    inicioPrevisto TIMESTAMP NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    CONSTRAINT empresa_leilao_fk FOREIGN KEY (vendedor) REFERENCES empresa (id) ON DELETE NO ACTION
);

CREATE TABLE unidade (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nome VARCHAR(128) NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP
);

CREATE TABLE lote (
    id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    numeroLote INTEGER,
    descricao VARCHAR(60) NOT NULL,
    quantidade NUMERIC(10, 2) NOT NULL,
    valorInicial NUMERIC(16, 2),
    unidade INTEGER NOT NULL DEFAULT 1,
    leilao INTEGER NOT NULL,
    createdAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    updatedAt TIMESTAMP NOT NULL DEFAULT LOCALTIMESTAMP,
    CONSTRAINT leilao_lote_fk FOREIGN KEY (leilao) REFERENCES leilao (id) ON DELETE CASCADE,
    CONSTRAINT unidade_lote_fk FOREIGN KEY (unidade) REFERENCES unidade (id) ON DELETE SET DEFAULT
);

CREATE TABLE comprador (
    empresa INTEGER NOT NULL,
    leilao INTEGER NOT NULL,
    PRIMARY KEY (empresa, leilao),
    CONSTRAINT empresa_comp_fk FOREIGN KEY (empresa) REFERENCES empresa (id) ON DELETE CASCADE,
    CONSTRAINT leilao_comp_fk FOREIGN KEY (leilao) REFERENCES leilao (id) ON DELETE CASCADE
);
